### ISSUE TITLE
vsc中展示带有中括号的语法的表达式渲染html语法失败，导致html高亮混乱

### ISSUE THREAD

**Issue by Yatoo2018** [microsoft/vscode-typescript-next#105]
![image](https://github.com/microsoft/vscode-typescript-next/assets/40135699/bed2b5b9-9780-4075-bad2-a1b2dce7cec4)

去掉 row[column.label] 就ok

![image](https://github.com/microsoft/vscode-typescript-next/assets/40135699/3464c194-57b8-4f3b-b96c-3c976a7a4253)

**Comment by mjbvz** [comment]
Closing as not filed in English
