### ISSUE TITLE
This extension breaks the auto import functionality in the latest version of VScode

### ISSUE THREAD

**Issue by Hasan-Mir** [microsoft/vscode-typescript-next#108]
This extension breaks the auto import functionality in the latest version of VScode, previously it was fine and I had no problem with it, but recently I discovered that it causese some auto import issues for some packages. for example I am using `@mui/material` and I don't have the auto import for its components:
![Screenshot 2024-01-23 174501](https://github.com/microsoft/vscode-typescript-next/assets/62181905/9730a271-26fa-404f-a514-d537cdc34db8)

But when I remove the `JavaScript and TypeScript Nightly` extension from vscode it works!
![image](https://github.com/microsoft/vscode-typescript-next/assets/62181905/09929bf3-dc03-4756-a17e-fd81cf7f40f0)

Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by mjbvz** [comment]
Closing as likely fixed. If you're still seeing a problem with the latest TS release, please open an issue against TypeScript
