### ISSUE TITLE
Static type checking returns inconsistent results for arrow functions and normal functions

### ISSUE THREAD

**Issue by quark-ftc** [microsoft/vscode-typescript-next#118]
When I write a type-checking function using a normal function (without the is predicate), the plugin prompts an error
![11111111111](https://github.com/microsoft/vscode-typescript-next/assets/35005124/e93f1fa7-2226-49e5-abdc-0a0079e7072a)
But when I rewrite it as an arrow function, the plugin doesn't give an error, but the TS compiler still gives an error
![222222222222](https://github.com/microsoft/vscode-typescript-next/assets/35005124/3f46fb2a-17dd-47fd-a67a-223e98af90b9)

**Comment by mjbvz** [comment]
Please also share the code as text, not just screenshots

**Comment by mjbvz** [comment]
Closing as more info needed
