### ISSUE TITLE
can't download extension

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode-typescript-next#12]
Manually downloading using the vsix link given by notification also failed even if configure the proxy.

![screenshot_2020-11-13_00-01-55](https://user-images.githubusercontent.com/41773861/98964177-77ed2980-2543-11eb-84da-889bf104d1eb.png)

**Comment by tjx666** [comment]
@mattetti

**Comment by mjbvz** [comment]
This doesn't seem related this this extension
