### ISSUE TITLE
Type check error (critical)

### ISSUE THREAD

**Issue by matvejs16** [microsoft/vscode-typescript-next#124]
Type: <b>Bug</b>

Different behaviour since ``v5.5.20240513``

### Example code:
```typescript
let strings: string = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
strings = 1;
```
As you can see in [Playground Link](https://www.typescriptlang.org/play/?ts=5.6.0-dev.20240615#code/DYUwLgBAzmBOCWA7A5lAXNOTkQLwQHIBBAIQGEARAUQDEBxACQEkApAaQBkBZAOQHkACgEUASgGUAKgFUAagHUAGgE0AWgQDcAKBgIUUPBACM6oA) there is no typescript version error.

Q: What's wrong?
A: Not showing typescript types error

## Current behaviour ``v5.6.20240615``: 
![image](https://github.com/microsoft/vscode-typescript-next/assets/74150728/37fb10c3-a207-4f12-bf0c-34579f2546eb)

## Expected behaviour ``v5.5.20240505``:
![image](https://github.com/microsoft/vscode-typescript-next/assets/74150728/732b6046-7531-47db-9c8c-61b4076782f2)

Extension version: 5.6.20240615
VS Code version: Code - Insiders 1.91.0-insider (0da59bdde2339d6ba632524dc8f3fb6f4b8a2bcb, 2024-06-14T10:10:07.014Z)
OS version: Linux x64 5.15.0-102-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4262)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|62.67GB (56.08GB free)|
|Process Argv|/var/www/public_web/chinahubTG/client.code-workspace --crash-reporter-id dbf6f9d6-97b9-4055-97a3-82784f7dc748|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
showvideot:31016890
chatpanelt:31014475
g316j359:31013175
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupyter:31046869
2f103344:31071589
nb_pkg_only:31057982
nativerepl2:31071685
refactort:31073763

```

</details>

**Comment by mjbvz** [comment]
Doesn't repo for me with the latest version. Possibly an issue with one of the TS builds but I don't recall seeing this in the past few weeks either

**Comment by matvejs16** [comment]
I haven't mentioned that this issue happens only in Vue project files, and that's not only in .vue file, but in .ts files also, idk maybe that's something wrong with Vue typescript

**Comment by mjbvz** [comment]
Thanks. Vue support comes from the Vue extension, which can sometime also interfere with features in normal TS files. Please file an issue against your Vue extension for this
