### ISSUE TITLE
Syntax highlight stopped working

### ISSUE THREAD

**Issue by MatthijsReyers** [microsoft/vscode-typescript-next#125]
Typescript syntax highlighting no longer works for me (all code just appears white), if I disable the typescript nightly plugin the syntax highlighting appears again.

When I try to debug the syntax highlighting vs code tells me:
```
No TM Grammar registered for this language.
```

Edit: this is also the case for Javascript files

**Comment by mjbvz** [comment]
Works fine for me

![Image](https://github.com/user-attachments/assets/43d97927-7e66-481c-8471-081597aa15ac)

What VS Code and extension version are you using? Also try disabling all other extensions

**Comment by MatthijsReyers** [comment]
```
$ code --version
1.86.2
903b1e9d8990623e3d7da1df3d33db3e42d80eda
x64
```

**Comment by MatthijsReyers** [comment]
Oh, I whatever the issue was it seems to have been fixed in the last 2 days because I can now enable the TypeScript Nightly plugin again without any problems... Well thanks anyway
