### ISSUE TITLE
Typescript/Javascript extension keeps crashing/restarting

### ISSUE THREAD

**Issue by rlsawyer33** [microsoft/vscode-typescript-next#14]
Open any javascript file. You will see "Initializing JS/TS language features" constantly in the status bar, then a popup that says "The TypeScript language service died unexpectedly 5 times in the last 5 Minutes."

I looked at other issues, and tried some of the solutions:
1. Install typescript@next. No change.
2. Restart JS service. Does work initially. However any edit to a JS file causes it to happen again.

**Comment by mjbvz** [comment]
Please file issues like against TypeScript or VS Code
