### ISSUE TITLE
TypeScript undefined is not interpreted correctly

### ISSUE THREAD

**Issue by tonsnoei** [microsoft/vscode-typescript-next#16]
Since one of the last nightly builds error detection contains a bug. 

If we have the following code:

```
class X {
   public name?: string; 
}
```

It does not understand that it is the same as:

```
class X  {
  public name: string | undefined;
}
```

If we have code that uses the first example:
```
const x = new X();
x.name = undefined;
```
It will show an error detection line below the second row. The correction argues that undefined may not be applied to x.name. 

That is strange right!?

**Comment by mjbvz** [comment]
Please file these types of issues against TS (but this one is by-design https://github.com/microsoft/TypeScript/pull/43947)
