### ISSUE TITLE
"Extract to method in class" in angular template not working correctly

### ISSUE THREAD

**Issue by stefanrybacki** [microsoft/vscode-typescript-next#18]
Also see: https://github.com/angular/vscode-ng-language-service/issues/533

**Describe the bug**

"Extract to method in class" ability doesn't seem to behave correctly on a inline template function call. In below

**To Reproduce**

see GIF for clear reproduction. the inline template is missing the function addChildElement and is listed correctly. Using the autosuggested 'extract method' call in context menu removes the whole template properly and swaps it with a templateURL one, with a weird function call.

![image](https://user-images.githubusercontent.com/9585787/71540948-89116400-298c-11ea-918f-641ecfa621b0.gif)

**Comment by mjbvz** [comment]
Please file this issue against typescript itself
