### ISSUE TITLE
Typescript Intellisense not working with .tsx files

### ISSUE THREAD

**Issue by MohammadArik** [microsoft/vscode-typescript-next#19]
I was working in a react project and after an update or something typescript intellisense was not working in any .tsx file. I tried to reload, re-install, disabling and re-enabling but didn't work. Then I changed the language mode from **Typescript React** to **Typescript** and intellisense working file then. But I need to make intellisense work with Typescript React. How to fix it???

I am using Kubuntu 21.04 and latest version of VS Code for Debian based Linux systems.

**Comment by mjbvz** [comment]
Please file your issue against TypeScript or
