### ISSUE TITLE
Extension causes error  'Type instantiation is excessively deep and possibly infinite'

### ISSUE THREAD

**Issue by bailinca** [microsoft/vscode-typescript-next#22]
Related info here:
https://github.com/react-hook-form/react-hook-form/issues/6679#issuecomment-934299930

**Comment by danielsitepu36** [comment]
I've tried to downgraded to the last `v4.4` version (1 month ago) and the error is gone.
But, it is still unknown whether the error is in the extension or in the react-hook-form package

**Comment by mjbvz** [comment]
Please file this against TypeScript itself
