### ISSUE TITLE
Not showing me jsx attribute auto completions

### ISSUE THREAD

**Issue by lakshits11** [microsoft/vscode-typescript-next#23]
Issue Type: <b>Bug</b>

It is not showing me jsx attribute autocompletion. Like this:

![image](https://i.stack.imgur.com/AW8vS.png)

but when I type on, I am not getting any suggestions, disabling this extension solves the problem.

Extension version: 4.6.20211102
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:58:13.605Z)
OS version: Linux x64 5.13.19-2-MANJARO
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|7.68GB (2.27GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 56bb7de1-50cb-417b-af3f-c630f73a4a9b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by mjbvz** [comment]
Please file this against TypeScript itself
