### ISSUE TITLE
Theme related bug in v4.6.20220201

### ISSUE THREAD

**Issue by mrinc** [microsoft/vscode-typescript-next#26]
Hey,

I haven't looked into it, however just letting everyone know.

The latest version seems to break the theme for js/ts files:
v4.6.20220201
![image](https://user-images.githubusercontent.com/4445914/152227317-ca472bb8-c3f2-4cbb-9255-f8350e515326.png)

v4.6.20220131
![image](https://user-images.githubusercontent.com/4445914/152227530-4fc07cc9-94b1-429d-a564-c4aff3124798.png)

**Comment by mjbvz** [comment]
Syntax highlighting works fine for me using the latest version of the extension

Please make sure another extension is not causing this issue. If you still see this, then share the code (as text) that causes the problems

**Comment by mrinc** [comment]
Hey,

Latest is now fine....

But like I said js/ts files.... every single files highlighting was just gone.

I disabled all other extensions, rebooted PC all the normal jazz, just would not work.

Downgraded, and it was fine.

So seems to have been a bug or something in that nightly build specifically and fixed on the next build.
