### ISSUE TITLE
esinterop false positive  reporting

### ISSUE THREAD

**Issue by xenoterracide** [microsoft/vscode-typescript-next#31]
every single esInterop potential dependency is marked as an error, however, the relevant tsconfigs all have it enabled

```
❯ find . -name tsconfig.json | grep -v node_modules
./tests/tsconfig.json
./packages/models/tsconfig.json
./packages/workflow-module/tsconfig.json
./packages/validation/tsconfig.json
./tsconfig.json
./front-end/tsconfig.json
./front-end/src/tsconfig.json
./back-end/tsconfig.json
❯ find . -name tsconfig.json -exec grep -i esmodule '{}' + | grep -v node_modules
./packages/models/tsconfig.json:    "esModuleInterop": true,
./packages/workflow-module/tsconfig.json:    "esModuleInterop": true,
./packages/validation/tsconfig.json:    "esModuleInterop": true,
./tsconfig.json:    "esModuleInterop": true,
./back-end/tsconfig.json:    "esModuleInterop": true,
```

```json
{
  "compilerOptions": {
    "strict": true,
    "resolveJsonModule": true,
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "../dist",
    "baseUrl": "./",
    "lib": ["ES2018"],
    "types": ["mocha"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "paths": {
      "*": ["node_modules/*", "*"]
    },
    "plugins": [
      {
        "name": "typescript-strict-plugin"
      }
    ]
  },
  "include": ["**/src/**/*"],
  "exclude": ["**/node_modules", "**/dist", "**/test-dist"]
}
```

```
Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0
```

<img width="916" alt="Screen Shot 2022-06-02 at 10 45 02 AM" src="https://user-images.githubusercontent.com/5517/171656392-91f4a7d6-b2b4-4cee-b0f3-9ac4bfdbc710.png">

**Comment by mjbvz** [comment]
Please file this against Typescript itself

**Comment by mjbvz** [comment]
I don't understand what you mean but this is definitely a TypeScript issue, not an issue with this extension

**Comment by xenoterracide** [comment]
actually, it's totally the extension. The problem stems from the fact that it doesn't read from the correct config file for the test files and there's no way to set a config file in the config settings, nor is there a way to tell the typescript daemon that runs for vscode to use any variables it provides. So the daemon as you start it, the default is that that is false, and thus the daemon vscode uses doesn't know any better since our test files are not compiled by our main `tsconfig.json`. I know this because our non test code does not show the same warning.

**Comment by mjbvz** [comment]
This extension only bundles a typescript build. It has no logic of its own
