### ISSUE TITLE
Type inference for Redux toolkit is broken

### ISSUE THREAD

**Issue by WilliamZheng27** [microsoft/vscode-typescript-next#34]
See Also: https://github.com/reduxjs/redux-toolkit/issues/2320#issuecomment-1125688867
Relevant libraries:
- @reduxjs/toolkit@1.8.3

Minimal reproduction:
```typescript
import { createSlice, PayloadAction } from '@reduxjs/toolkit';

interface State {
  singleKey: string;
}

const initialState: State = {
  singleKey: '',
};

const slice = createSlice({
  name: 'slice',
  initialState,
  reducers: {
    test: (state, action: PayloadAction<string>) => {
      state.singleKey = action.payload;
    },
  },
});

export default slice.reducer;
```
VSCode identified `state` as `any`:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/22299002/178932599-e7df4cb7-71ea-4df9-aebb-8bf4b15e8320.png">
<img width="385" alt="image" src="https://user-images.githubusercontent.com/22299002/178932726-e70750d6-c26d-49e3-acc3-b6e5cd9b74dc.png">
With this extension disabled:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/22299002/178932944-a494748c-ca45-4287-bc84-a127f618b66f.png">

**Comment by mjbvz** [comment]
Please file this against the TypeScript project
