### ISSUE TITLE
更新到 5.0.20221116 版本，导致语法高亮失效问题

### ISSUE THREAD

**Issue by qiaofugui** [microsoft/vscode-typescript-next#45]

**Comment by Just1dream** [comment]
先禁用掉JavaScript and TypeScript Nightly插件吧

**Comment by qiaofugui** [comment]
> 

先使用 2.0.20221115 版本就好了

**Comment by Just1dream** [comment]
确实

**Comment by link-zh** [comment]
先禁用掉吧，早上来发现高亮没了，找了半天才找到这里

**Comment by bettermonster** [comment]
我也这样了，找半天 额

**Comment by roo12589** [comment]
看半天才找到 没想到是这个插件

**Comment by 948764321** [comment]
+1，找了半天，坑死了

**Comment by doornot** [comment]
> > 
> 
> 先使用 2.0.20221115 版本就好了

Install Another Version: `5.0.20221115`

![截屏2022-11-17 上午11 26 46](https://user-images.githubusercontent.com/10323102/202347663-c7acfa07-a543-4275-9a28-df0134e3ce7d.png)

**Comment by HiChen404** [comment]
+1

**Comment by SpiritQAQ** [comment]
笑死，今天时间都浪费在这上面了

**Comment by AsteriskZuo** [comment]
我把 vscode 卸载了一遍，包括所有缓存内容，竟然是它导致的。nightly版本太不靠谱了吧。

**Comment by tangdw** [comment]
找了半天，原来是这个插件。
装了 Visual Studio Code - Insiders 才反应过来，是插件的功能，不是自带的

**Comment by mjbvz** [comment]
Duplicate of #43
