### ISSUE TITLE
Take colors aways

### ISSUE THREAD

**Issue by azuls123** [microsoft/vscode-typescript-next#46]
Type: <b>Bug</b>

this extensios makes gray some reserved words in javascript code, making it confusing

Extension version: 5.0.20221116
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.96GB (10.06GB free)|
|Process Argv|--crash-reporter-id 8bf7a74e-2332-4c0b-b611-a22dceba772a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyonecf:30548226
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30602488
gswce1:30612156
iaj6b796:30608729
dbltrim-noruby:30604474

```

</details>

**Comment by drewbitt** [comment]
Agreed - 5.0.20221116 removes code syntax highlighting

**Comment by ethanruiyu** [comment]
me too!!

**Comment by SOPLAY** [comment]
me too! b

**Comment by UBamtol** [comment]
me too!!!

**Comment by Mallang-Mallang** [comment]
me too!

**Comment by tohsaka888** [comment]
me too!

**Comment by fahmij8-tkp** [comment]
happened to me as well

**Comment by ericpeweh** [comment]
same here

**Comment by mohamadalsalty** [comment]
Same here

**Comment by taitasu555** [comment]
yes me too

**Comment by deny-wijaya** [comment]
> me too. So I downgrade the version to 5.0.20221115.

how to do that ?

**Comment by tohsaka888** [comment]
> > me too. So I downgrade the version to 5.0.20221115.
> 
> how to do that ?

![image](https://user-images.githubusercontent.com/58759688/202353332-25cc5ebf-fcc5-4b3b-b2f7-752ae9daefe7.png)

**Comment by tohsaka888** [comment]
> > me too. So I downgrade the version to 5.0.20221115.
> 
> how to do that ?

![image](https://user-images.githubusercontent.com/58759688/202353406-273c266a-0f3e-4b5e-af26-3b031dc655b6.png)

**Comment by deny-wijaya** [comment]
> > > me too. So I downgrade the version to 5.0.20221115.
> > 
> > 
> > how to do that ?
> 
> ![image](https://user-images.githubusercontent.com/58759688/202353406-273c266a-0f3e-4b5e-af26-3b031dc655b6.png)

got it thank u

**Comment by fahmij8-tkp** [comment]
duplicate here https://github.com/microsoft/vscode-typescript-next/issues/43

**Comment by Darshana-Waasala** [comment]
> me too. So I downgrade the version to 5.0.20221115.

Me too got the issue, I disabled the extension. But how to downgrade?

**Comment by Darshana-Waasala** [comment]
> 

by right clicking on the extension,
![image](https://user-images.githubusercontent.com/17754250/202354352-0524608b-bfc5-408a-9a23-5e76653fbeab.png)

**Comment by sahilchraya** [comment]
[Screencast from 17-11-22 11:25:58 AM IST.webm](https://user-images.githubusercontent.com/72769401/202367992-b6924a3a-69fc-4817-8439-5643ebdfe658.webm)
Hope this helps.

**Comment by Ranaxl693** [comment]
This is a problem for me as well. However, by downgrading Javascript and typescript Nightly extension to this version 5.0.20221115, the problem has been resolved.

**Comment by MandaNyAina** [comment]
Changing version to 5.0.20221115 work for me. Thanks


> > > > me too. So I downgrade the version to 5.0.20221115.
> > > 
> > > 
> > > how to do that ?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/58759688/202353406-273c266a-0f3e-4b5e-af26-3b031dc655b6.png)
> 
> got it thank u

**Comment by rumar-karta** [comment]
Same here thanks

**Comment by toyo30** [comment]
Thank you! I solved problem. After changing version, if you also have trouble about it, just reload vscode.

**Comment by ddtch** [comment]
that's why I hate auto-updates. it was so annoying, and finally, a solution!

**Comment by yogga18** [comment]
> me too. So I downgrade the version to 5.0.20221115.

it worked for me, thanks

**Comment by jfilipeferreira96** [comment]
Yep downdrading is the solution

**Comment by KiddoV** [comment]
Same for me, I lost almost all syntax highlighting. Thanks for the downgrade suggestion!!

**Comment by dominikdnd** [comment]
Same here

**Comment by syJSdev** [comment]
same here
