### ISSUE TITLE
Automatic Semicolon Insertion issue

### ISSUE THREAD

**Issue by Luxcium** [microsoft/vscode-typescript-next#5]
I was editing my Issue and my corrector crashed my browser...

Ok so I will try to be short and concise: the problem is on line 4 to 5 (11 & 12 on the image)  and the related code I was working on is on [GitHub commit: aeefa22e38](https://github.com/Luxcium/questrade-ts/blob/aeefa22e38c5e82f84cebf9597b6b1f6f96665c0/src/core/functions/private/questrade/index.ts)

<img width="529" alt="Capture d’écran, le 2019-09-19 à 04 32 14" src="https://user-images.githubusercontent.com/42672814/65230501-f82d1180-da9b-11e9-9207-4e206dfb2e66.png">

I am using a clean and fresh out of the box version of VSCode "portable" with only «ms-vscode.vscode-typescript-next» installed

In the code in my example, the missing semicolon would have not really been an issue because I am using the property `combinedBalances`but the same problem happens if the property reference a function (i.e. using a method)  my code will require to use const/let/var thus avoiding this issue altogether (or I could have added the semicolon myself) ut the problem is that I rely on autocompletion/prettier/linter to do that part of the job...

I fell like its a bug and I wish you will have enough pieces of information to find a solution maybe I should add the semi or maybe my linter should do it but I feel the autocompletion should have not added a problem right away... 

Tell me how I can be part of the solution in a constructive way so you can fix the problem... 

LANGUAGE: The best evolution of ES262 specification ever (TypeScript)
IDE: The amazing VISUAL STUDIO CODE 
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by mjbvz** [comment]
I don't think this is an issue with this extension. Please file an issue [against typescript itself](https://github.com/Microsoft/TypeScript/issues)

**Comment by Luxcium** [comment]
What type of problem is it. ? I don’t know how to describe it more than I did here... can you point me in a direction before I take the time to open a ticket (issue) with them ...

**Comment by mjbvz** [comment]
Try filling out the [TypeScript issue template](https://github.com/microsoft/TypeScript/issues/new?template=Bug_report.md). Describe what you were doing, what the expected behavior was, and what went wrong
