### ISSUE TITLE
Extension Crashing after VSCode update

### ISSUE THREAD

**Issue by Shivam60** [microsoft/vscode-typescript-next#6]
### Platform information

Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Name: JavaScript and TypeScript Nightly
Id: ms-vscode.vscode-typescript-next
Description: Enables typescript@next to power VS Code's built-in JavaScript and TypeScript support
Version: 3.8.20191121
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

### Issue:
After the recent update of visual studio code to 1.40.1(User setup) the Extension is crashing repeatedly 

### Repro Steps 
Load a big project. In some time the extension will crash
![image](https://user-images.githubusercontent.com/13963817/69399143-1240d580-0d13-11ea-82e1-d8f6acd9a967.png)

**Comment by mjbvz** [comment]
This is not an issue with this extension; please file it against vs code
