### ISSUE TITLE
vscode-styled-components extension's css intellisense is not working after updating to latest version

### ISSUE THREAD

**Issue by booooora** [microsoft/vscode-typescript-next#61]
Hi, I'm using `JavaScript and TypeScript Nightly` with `vscode-styled-components` extension.
But after updating `JavaScript and TypeScript Nightly` to latest version, `vscode-styled-components` extension's css intellisense (suggestion) is not working. 
When I uninstall or downgrade `JavaScript and TypeScript Nightly` to v5.0.20221103, `vscode-styled-components` css suggestion is working as expected.

`JavaScript and TypeScript Nightly` v5.0.202211170 -> css suggestion not working
(downgrading to v5.0.20221113 is also not working)
![image](https://user-images.githubusercontent.com/96520714/202969987-85a21ac9-472d-457e-8fdd-bb00b3e987aa.png)

`JavaScript and TypeScript Nightly` v5.0.20221103 -> css suggestion working
![image](https://user-images.githubusercontent.com/96520714/202970062-27953bc1-a075-4ceb-9bb4-0e0e6fbd6a34.png)

Extension version: v5.0.202211170
VS Code version: Code 1.73.1 (Universal)
OS version: macOS Ventura
vscode-styled-components extension version: v1.7.5

**Comment by ricardroberg** [comment]
Exactly the same here

**Comment by mjbvz** [comment]
Please file this against the styled components extension. It likely needs to be updated to support TS 5+

**Comment by mjbvz** [comment]
@jasonwilliams Can you please open an issue against TypeScript for this? They may have some idea of what changed in 5.0
