### ISSUE TITLE
extension settings not showing

### ISSUE THREAD

**Issue by scarf005** [microsoft/vscode-typescript-next#62]
![_02](https://user-images.githubusercontent.com/54838975/202985475-391de112-d1de-4c64-ae27-6b515ef72e74.png)

in contrast to other extensions:
![_03](https://user-images.githubusercontent.com/54838975/202985483-181bd62c-0fbd-4bd1-8277-d9692f7304cd.png)

```
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-53-generic
Sandboxed: No
```

**Comment by mjbvz** [comment]
This extension doesn’t have any user settings
