### ISSUE TITLE
Extension suddenly broke

### ISSUE THREAD

**Issue by hyoretsu** [microsoft/vscode-typescript-next#67]
This week, syntax highlighting stopped working on TS/TSX files. At first I thought it's my PC, but restarting didn't fix it. I then checked `Inspect Editor Tokens and Scopes` and it says "No TM Grammar registered for this language." nor can I find ts-next in `Select TypeScript Version`. If I uninstall the extension, everything starts workign again.

I'm using VSCode v1.74.3

**Comment by hyoretsu** [comment]
v5.0.202301160

**Comment by mjbvz** [comment]
Works fine for me

Does this reproduce if you disable other extensions?

**Comment by hyoretsu** [comment]
It still happens even after disabling all installed extensions. I don't think it matters, but I'm using WSL2 Remote on Windows.

**Comment by mjbvz** [comment]
Does it work locally (not on wsl)?
