### ISSUE TITLE
Latest Update Causing Auto Complete Errors in React/JSX

### ISSUE THREAD

**Issue by Crazyloon** [microsoft/vscode-typescript-next#70]
In the last couple of days, I've been having issues with auto-complete in VS code and I think it's related to this extension because disabling this extension resolved my issue.

If I have a React Component like this...

```
const Comp = () => {
  const [data, setData] = useState();
  return <div>...</div>;
};
```

...and I want to set a property on the div for data (or anything really). If I type '`da`' and then let VS Code auto-complete, I get "`data={}`" instead of just "`data`".

```
const Comp = () => {
  const [data, setData] = useState();
  return <div data={data={}}></div>;
};
```

I should expect auto-complete to just provide "data" like this...

```
const Comp = () => {
  const [data, setData] = useState();
  return <div data={data}></div>;
};
```

I've tried to disable all extensions except for this one, and can reliably reproduce the error.

Can anyone reproduce this while in the TypeScript React language mode?

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/52288
