### ISSUE TITLE
typescript server stopping

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode-typescript-next#73]
Type: <b>Bug</b>

typescript server is stopping
![image](https://user-images.githubusercontent.com/9264813/216538973-f74a0210-e7bd-4b94-9f0e-75a465e30e01.png)

![image](https://user-images.githubusercontent.com/9264813/216542117-46311e5d-1135-4da1-aa7c-56486e0acdd3.png)

![image](https://user-images.githubusercontent.com/9264813/216544708-b2b3fe08-9a30-497e-b72c-bb78dd5648a7.png)

Extension version: 5.0.202302020
VS Code version: Code - Insiders 1.76.0-insider (c4a609f94329b17d91cd13a4fd113d1abfe5ec1f, 2023-02-03T05:23:17.202Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (3.47GB free)|
|Process Argv|--crash-reporter-id e5294b27-02c9-4438-b8f3-90acb1091b3b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
showlangstatbar:30657381

```

</details>

**Comment by mjbvz** [comment]
https://github.com/microsoft/vscode/issues/173258

Please don't open duplicate issues across repositories

**Comment by sanket-bhalerao** [comment]
i was not aware which repository/extension this was originated from hence created it at 2 places.
