### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Anprotaku** [microsoft/vscode-typescript-next#78]
I dont really know where to post this suggestion for a feature. (If wrong place please tell me)
But a suggestion to show in code whether or not you are copying a value or doing a reference to an object

![image](https://user-images.githubusercontent.com/126538099/230605264-4659fe11-bf69-4510-8127-b8fe0742aaca.png)
Something like the above that show us what type something is without typing it out. 
I think it would be usefull if we had something similar that shows us if we are copying or referencing a variable.
![image](https://user-images.githubusercontent.com/126538099/230605417-052f89a6-6aa6-4849-89c9-242a1fdb7cfc.png)
Something around that assignment to show that obj2 is a reference and not a copy could possibly be helpful?

**Comment by mjbvz** [comment]
This sounds like a good candidate for an extension. See vscode's InlayHint api for how to contribute these annotations

**Comment by Anprotaku** [comment]
How would i go about getting references and the context of the code, I can use InlayHint api for displaying information, but how would i go about getting it? Is there some api or something i can use?
