### ISSUE TITLE
some suggestions are not appearing

### ISSUE THREAD

**Issue by Bader-Idris** [microsoft/vscode-typescript-next#80]
the extension does not suggest some methods such as e.stopPropagation(), and e.preventDefault().
and another issue is that the extension doesn't suggest methods when I create a function, it helps only when it understands that this var or object is capable of specific methods

**Comment by mjbvz** [comment]
Please file this issue against typeScript: https://github.com/microsoft/TypeScript/issues/new/choose

Be sure to include example code
