### ISSUE TITLE
Multiline JSDoc not formatted properly in hover-over

### ISSUE THREAD

**Issue by sebastiantf** [microsoft/vscode-typescript-next#81]
Multiline JSDoc still requires a blank line to trigger a line break in hover tip. Else it just concatenates everything into a single line

Is this the expected behavior?

<img width="725" alt="Screenshot 2023-05-16 at 12 38 42 PM" src="https://github.com/microsoft/vscode-typescript-next/assets/36922376/635190d7-9448-4908-ac89-a7de07ec1816">

<img width="711" alt="Screenshot 2023-05-16 at 12 38 49 PM" src="https://github.com/microsoft/vscode-typescript-next/assets/36922376/c856e9a7-bc6c-4b98-8f57-d3b02bbf4eae">

**Comment by mjbvz** [comment]
Yes, the content is treated as markdown

Also in the future please file issues like this against either TypeScript or VS Code directly
