### ISSUE TITLE
Can't format ts files

### ISSUE THREAD

**Issue by elvesshuang** [microsoft/vscode-typescript-next#84]
Issue Type: <b>Bug</b>

When I open the VS Code command palette, type the " TypeScript: Select TypeScript version", there is no matching result show below。I have installed the JavaScript and TypeScript Nightly, and I can't format ts files

And thd VS Code warning: the TypeScript lauguages hase died 5 times ,and it will not be restarted

Extension version: 5.2.20230605
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:33:47.663Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by singhparveen** [comment]
Same. No setting in the VScode command prompt

**Comment by mjbvz** [comment]
> VS Code version: Code 1.45.1 

This is a very old VS Code version. Please update to at least the latest stable release: 1.80+
