### ISSUE TITLE
我把你妈杀了，最新版本破坏了我的vscode，还不给旧版本链接我下载，我杀你妈的

### ISSUE THREAD

**Issue by l406054531** [microsoft/vscode-typescript-next#86]
我把你妈杀了，最新版本破坏了我的vscode，还不给旧版本链接我下载，我杀你妈的

**Comment by mjbvz** [comment]
Please only post issues in English. See this guide for help: https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by DrMagicalStone** [comment]
I see your BEAUTIFUL sentence. To produce wonderful software is what everyone wants, but not anyone's responsibility.
