### ISSUE TITLE
no TypeScript: Select TypeScript version command 

### ISSUE THREAD

**Issue by wufeng87** [microsoft/vscode-typescript-next#9]
I installed JavaScript and TypeScript Nightly extention, but I could not see the TypeScript: Select TypeScript version command in the vs code command palette.

more detail goes here:
https://stackoverflow.com/questions/60504441/typescript-intellisense-not-worked-in-my-vscode

Thanks

**Comment by mjbvz** [comment]
This command comes from VS Code itself, not this extension

Make sure you have not disabled the builtin `JavaScript and TypeScript language features` extension (search `@builtin` in the extensions view to check this)
