### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by SergioFanelliJr** [microsoft/vscode-typescript-next#95]
Type: <b>Bug</b>

"The syntax highlighting stopped working and I discovered the error while generating a bisect."

Extension version: 5.3.20231010
VS Code version: Code - Insiders 1.84.0-insider (6a7a661757dec1983ff05ef908a2bbb75ce841e0, 2023-10-11T05:34:23.077Z)
OS version: Windows_NT x64 10.0.23560
Modes:
Connection to 'wsl+Ubuntu' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.64GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/sergiofanellijr/food-guardian --remote=wsl+Ubuntu --crash-reporter-id 97c4486f-42fb-4485-bff9-46a376475471|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+Ubuntu' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
showlangstatbar:30737417
57b77579:30687741
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
synctok:30821570
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmypywwcf:30841057
pythonmpsinfo:30842935
dsvsc015:30821418
pythontestfixt:30826906
pythonfb280951:30830809
pythonregdiag:30842812
pythonmypyd1:30850305
pythoncet0:30848247

```

</details>

**Comment by mjbvz** [comment]
Please share example code which demonstrates the issue

**Comment by ahmadmu** [comment]
I'm having the same issue, the vscode typescript version is 5.1.3. It suddenly stopped working a couple of days ago.

**Comment by mjbvz** [comment]
Closing as no repo steps were provided
